//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLĐRenLuyen.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HocKy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_HocKy()
        {
            this.tbl_TieuChi = new HashSet<tbl_TieuChi>();
        }
    
        public long ID { get; set; }
        public string HocKy { get; set; }
        public Nullable<long> NamHoc_ID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TieuChi> tbl_TieuChi { get; set; }
        public virtual tbl_NamHoc tbl_NamHoc { get; set; }
    }
}
